#!/bin/bash
# The MIT License (MIT)
# 
# Copyright (c) 2015 Tom Hancocks
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

DIR=`pwd`

# Options
export PREFIX="$HOME/opt/cross"
export TARGET="i686-elf"
export PATH="$PREFIX/bin:$PATH"
DEST="/tmp/osdev"

SHOW_HELP="no"
FORCE_INSTALL="no"
PURGE="no"
for opt do
    case "$opt" in
    --prefix=*) PREFIX=`echo $opt | cut -d '=' -f 2`
    ;;
    --target=*) TARGET=`echo $opt | cut -d '=' -f 2`
    ;;
    --force) FORCE_INSTALL="yes"
    ;;
    --download) DEST=`echo $opt | cut -d '=' -f 2`
    ;;
    --purge) PURGE="yes"
    ;;
    --help) SHOW_HELP="yes"
    ;;
    esac
done

if [ ${SHOW_HELP} == "yes" ]; then
cat <<EOF

Usage: ./toolchain/gcc/prepare-gcc-linux [options]
Options: [defaults in brackets after descriptions]

In order for this tool to run correctly, you will need bash, apt and 
a working version of clang or gcc.

EOF
echo "Standard Options"
echo "--help        Display script options"
echo "--target      The architecture the toolchain should target [${TARGET}]"
echo "--prefix      Where the toolchain should placed [${PREFIX}]"
echo "--download    Where any required packages should be downloaded to"
echo "              [${DEST}]"
echo "--force       Forces the script to proceed even if the tools are already"
echo "              installed."
echo "--purge       Purges all previously downloaded packages."
echo "--brew        Installs Homebrew if it is not already present."
exit 1
fi

# Testing for libgmp3-dev
if [ $(dpkg-query -W -f='${Status}' libgmp3-dev 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mlibgmp3-dev not present... installing\033[0m"
    sudo apt-get install libgmp3-dev
else
    echo ""
    echo "\033[1;32mlibgmp3-dev already installed\033[0m"
fi

# Testing for libmpfr-dev
if [ $(dpkg-query -W -f='${Status}' libmpfr-dev 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mlibmpfr-dev not present... installing\033[0m"
    sudo apt-get install libmpfr-dev
else
    echo ""
    echo "\033[1;32mlibmpfr-dev already installed\033[0m"
fi

# Testing for libmpc-dev
if [ $(dpkg-query -W -f='${Status}' libmpc-dev 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mlibmpc-dev not present... installing\033[0m"
    sudo apt-get install libmpc-dev
else
    echo ""
    echo "\033[1;32mlibmpc-dev already installed\033[0m"
fi

# Testing for texinfo
if [ $(dpkg-query -W -f='${Status}' texinfo 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mtexinfo not present... installing\033[0m"
    sudo apt-get install texinfo
else
    echo ""
    echo "\033[1;32mtexinfo already installed\033[0m"
fi

# Testing for make
if [ $(dpkg-query -W -f='${Status}' make 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mmake not present... installing\033[0m"
    sudo apt-get install make
else
    echo ""
    echo "\033[1;32mmake already installed\033[0m"
fi

# Testing for nasm
if [ $(dpkg-query -W -f='${Status}' nasm 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo ""
    echo "\033[1;31mnasm not present... installing\033[0m"
    sudo apt-get install nasm
else
    echo ""
    echo "\033[1;32mnasm already installed\033[0m"
fi

# Download the GCC & Binutils Sources
# Download the sources
GCC_4_9_SOURCE="https://ftp.gnu.org/gnu/gcc/gcc-4.9.0/gcc-4.9.0.tar.gz"
BINUTILS_2_24_SOURCE="https://ftp.gnu.org/gnu/binutils/binutils-2.24.tar.gz"
GCC_ARCHIVE=${DEST}/gcc49.tar.gz
BIN_UTILS_ARCHIVE=${DEST}/binutils.tar.gz

# Ensure the destination folder exists
if [ ${PURGE} == "yes" ]; then
    rm -rf ${DEST}
fi

mkdir -p ${DEST}

if [ ! -f ${BIN_UTILS_ARCHIVE} ]; then
    echo ""
    echo "\033[1;36mDownloading ${BINUTILS_2_24_SOURCE}\033[0m"
    curl -# ${BINUTILS_2_24_SOURCE} > ${BIN_UTILS_ARCHIVE}
fi

if [ ! -f ${GCC_ARCHIVE} ]; then
    echo ""
    echo "\033[1;36mDownloading ${GCC_4_9_SOURCE}\033[0m"
    curl -# ${GCC_4_9_SOURCE} > ${GCC_ARCHIVE}
fi

# Unpack the packages and prepare for building the toolchain
BUILD_SRC=${DEST}
BIN_UTILS_DIR=${BUILD_SRC}/binutils-2.24-build
GCC_DIR=${BUILD_SRC}/gcc-4.9-build

mkdir -p ${BIN_UTILS_DIR} ${GCC_DIR}

echo ""
echo "\033[1;33mExpanding downloaded packages\033[0m"
cd ${DEST}
tar -zxf ${BIN_UTILS_ARCHIVE}
tar -zxf ${GCC_ARCHIVE}

echo ""
echo "\033[1;33mConfiguring & Installing binutils\033[0m"
cd ${BIN_UTILS_DIR}
../binutils-2.24/configure --target=${TARGET} --prefix="${PREFIX}"\
    --with-sysroot --disable-nls --disable-werror
make
make install

which -- $TARGET-as || echo $TARGET-as is not in the PATH

cd ${GCC_DIR}
../gcc-4.9.0/configure --target=$TARGET --prefix="$PREFIX"\
    --disable-nls --enable-languages=c,c++ --without-headers
make all-gcc
make all-target-libgcc
make install-gcc
make install-target-libgcc

# add the tools to the users PATH and bash profile
echo ""
echo "\033[1;33mAdding tools to your profile & PATH\033[0m"
echo "export PATH=\"\$PATH:$PREFIX/bin\"" >> ~/.bash_profile


# Clean up... we've finished everything
cd ${DIR}
rm -rf ${DEST}


# Give a final wrap up message to the user with instructions.
cat <<EOF

\033[1;32mGCC Cross Compiler & Supporting Tools installed!\033[0m
The installation has now finished and the toolchain is now ready for use.
Unless you specified otherwise, the gcc compiler can be used by calling
\033[1;35mi686-elf-gcc\033[0m.

However there is one final step that you need to do before you can use it. That
is to run the following command:

    source ~/.bashrc

After that you will be good to go!
EOF